#!/bin/bash
####################
### frs-upload #####
version="0.5" ######
### JustBrowsing ###
####################

release="$1";
buildDir="/opt/jb-build"

userName="justbrowsing"
projName="justbrowsing"
alphaOne="j"
alphaTwo="ju"

testing="false"
dev="false"
nightly="false"
stable="false"

UPLOAD_OVA()
{
  ovaFile="${buildDir}/${projName}_${release}${1}.ova"
  echo "==> Uploading $ovaFile"
  if [ -f "$ovaFile" ]; then
    echo "==> rsync -avP -e ssh $ovaFile ${userName}@frs.sourceforge.net:/home/frs/project/${alphaOne}/${alphaTwo}/${folderDir}/"
    rsync -avP -e ssh "$ovaFile" ${userName}@frs.sourceforge.net:/home/frs/project/${alphaOne}/${alphaTwo}/${folderDir}/;
    ovaStatus="$?";
    if [ "$ovaStatus" != "0" ]; then
      rsync -avP -e ssh "$ovaFile" ${userName}@frs.sourceforge.net:/home/frs/project/${alphaOne}/${alphaTwo}/${folderDir}/;
      ovaStatus="$?";
    fi
    [ "$ovaStatus" = "0" ] || echo "==> OVA Upload failed";
  fi
}

UPLOAD_ISO()
{
  isoFile="${buildDir}/${projName}_${release}${1}.iso"
  echo "==> Uploading $isoFile"
  if [ -f "$isoFile" ]; then
    echo "==> rsync -avP -e ssh $isoFile ${userName}@frs.sourceforge.net:/home/frs/project/${alphaOne}/${alphaTwo}/${folderDir}/"
    rsync -avP -e ssh "$isoFile" ${userName}@frs.sourceforge.net:/home/frs/project/${alphaOne}/${alphaTwo}/${folderDir}/;
    isoStatus="$?";
    if [ "$isoStatus" != "0" ]; then
      rsync -avP -e ssh "$isoFile" ${userName}@frs.sourceforge.net:/home/frs/project/${alphaOne}/${alphaTwo}/${folderDir}/;
      isoStatus="$?";
    fi
    [ "$isoStatus" = "0" ] || echo "==> ISO Upload failed";
  fi
}

UPLOAD_README()
{
    if [ "$isoStatus" = "0" ]; then
      sleep 60;
      echo "==> rsync -avP -e ssh $buildDir/README.md ${userName}@frs.sourceforge.net:/home/frs/project/${alphaOne}/${alphaTwo}/${folderDir}/"
      rsync -avP -e ssh "$buildDir/README.md" ${userName}@frs.sourceforge.net:/home/frs/project/${alphaOne}/${alphaTwo}/${folderDir}/;
    else
      echo "==> ISO Upload failed";
    fi
}

UPLOAD_CHANGELOG()
{
    if [ "$isoStatus" = "0" ]; then
      sleep 60;
      echo "==> rsync -avP -e ssh $buildDir/pkglist.i686.txt ${userName}@frs.sourceforge.net:/home/frs/project/${alphaOne}/${alphaTwo}/${folderDir}/"
      rsync -avP -e ssh "$buildDir/pkglist.i686.txt" ${userName}@frs.sourceforge.net:/home/frs/project/${alphaOne}/${alphaTwo}/${folderDir}/;
    else
      echo "==> ISO Upload failed";
    fi
}


# Input parameters
[[ $@ = *testing* ]] && testing="true"
[[ $@ = *dev* ]] && dev="true"
[[ $@ = *nightly* ]] && nightly="true"
[[ $@ = *stable* ]] && stable="true"
echo "Build $release:";
echo "testing: $testing";
echo "dev: $dev";
echo "nightly: $nightly";
echo "stable: $stable";

# Sanity check
if [[ "$release" != [0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9] ]]; then
  echo "ERROR: invalid date";
  exit 1;
fi

# Upload ISO images
[ "$testing" = "true" ] && folderDir="${projName}/Testing" && UPLOAD_ISO "_testing"
[ "$dev" = "true" ] && folderDir="${projName}/DevEdition" && UPLOAD_ISO "_dev"
[ "$nightly" = "true" ] && folderDir="${projName}/Nightlies" && UPLOAD_ISO "_nightly" && UPLOAD_CHANGELOG
[ "$stable" = "true" ] && folderDir="${projName}" && UPLOAD_ISO && UPLOAD_CHANGELOG

# Upload OVA images
[ "$dev" = "true" ] && folderDir="${projName}/Virtual" && UPLOAD_OVA "_dev"
[ "$nightly" = "true" ] && folderDir="${projName}/Virtual" && UPLOAD_OVA "_nightly"
[ "$stable" = "true" ]  && folderDir="${projName}/Virtual" && UPLOAD_OVA

echo "[DONE]"
### END ###
