#!/bin/bash
####################
### qemu-iso #######
version="0.2" ######
### JustBrowsing ###
####################

isoFile="$1"
gpuDriver="$2"
[ -z "$gpuDriver" ] && gpuDriver="vmware"
#SDL_VIDEO_X11_DGAMOUSE=0 
QEMU_AUDIO_DRV=alsa qemu-system-x86_64 -enable-kvm -machine type=pc,accel=kvm -cpu host -soundhw ac97 -m 2000 -cdrom "$isoFile" -vga "$gpuDriver" -usbdevice tablet
